### ISSUE TITLE
How to prevent modelVersion parameter in response?

### ISSUE THREAD

**Issue by membersound** [jonpeterson/jackson-module-model-versioning#10]
```@JsonVersionedModel(propertyName = "modelVersion")```
private String modelVersion;

How can I prevent the model version field to be written into the response as json field? As of the sourcecode this is not supported yet, right?

I tried adding `@JsonIgnore` to the field, but that destroys the module converter...

**Comment by eklinger** [comment]
I believe you also need to set versionToSuppressPropertySerialization
